{% set name = "bayesian-optimization" %}
{% set version = "1.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 67a7abbad1213961a992b5fc9e1f659c13ce9db28dc0cd920d3398ddc11da9d4

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  host:
    - pip
    - python
  run:
    - numpy >=1.9.0
    - python
    - scikit-learn >=0.18.0
    - scipy >=0.14.0

test:
  imports:
    - bayes_opt

about:
  home: https://github.com/fmfn/BayesianOptimization
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Pure Python implementation of bayesian global optimization with gaussian processes.
  doc_url: https://github.com/fmfn/BayesianOptimization
  dev_url: https://github.com/fmfn/BayesianOptimization

extra:
  recipe-maintainers:
    - volpatto
