{% set name = "bayesian-optimization" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0c303e342ffa4f794902642fef08119929209152bd2b0de87f769b95f3da1870

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy >=1.9.0
    - python >=3.6
    - scikit-learn >=0.18.0
    - scipy >=0.14.0

test:
  imports:
    - bayes_opt

about:
  home: https://github.com/fmfn/BayesianOptimization
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Pure Python implementation of bayesian global optimization with gaussian processes.
  doc_url: https://github.com/fmfn/BayesianOptimization
  dev_url: https://github.com/fmfn/BayesianOptimization

extra:
  recipe-maintainers:
    - bwheelz36
    - till-m
    - volpatto
