travis:
  secure:
    BINSTAR_TOKEN: Ww9jlF8mUdQxU/vfklJsSJAEqcQxJt+pN5FmkFnWd/Vdj9YWu+gDD5EQpcwpWK/Te+NonA2+rX6DvGYCXL7uHSv1FW+oXWbsxK62DLg//CcuzDSIV0asGxyErHW8hk4snRZ+kNnvnuMJpRZv1bT764WYvr1Doei5IhoVQd7bTQb5v7LO9HH37qseUEIQa1VtUYtv/XzmSSNndyxiWBwcGEa+D3UKsyzGhk/pca/8V/fQNJrABhI3w5hDSn3lPpY1Q9UwCCtmLVHcGN+r6rywG4SY31HinbEJRFy+Scr8zEdnQe9P8aOpm/5/27zwdb7FpnzXcsHfg/Tc6vRqEnbyGEU4T7VaWwdggq5lagBuiqDgVa8/IbDkSVw8X/UB8PLxtEKx9AIL5VQo7hrrY3UXOwZcfNVV8tN86NUsQomG5k+L7gfJfIw0kN2nBfD1ZqaS0iCMfGY2I5sg3J3kw3BAyqChrKmUKorQgzecbhHNMTTXt2vfJUTOlJrS5NHJwWhgFVsSC2W33f3Jh9ztS0mQ+jSDk+I8Lav6oCpBAZhidIPbu0FrHKN6K+8on/m8RBYZnLbI9obwS8A0NnW/45dwOtTKA04pg0BM/0+jZayoMucDIMpAnbd92qmfOgWUaPf+Gf3xKp7b/Uc3dKiPu8Jhs2qoWCMvwwROBoyNop41qLo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
